exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 88
indent-width = 4
target-version = "py310"

[lint]
extend-select = [
  "UP",  # pyupgrade
  "E",   # pycodestyle
  "W",   # pycodestyle
  "C",   # mccabe
  "I",   # isort
  "N",   # pep8-naming
  "TRY", # tryceratops
]

ignore = ["UP015"]

[lint.mccabe]
max-complexity = 10

[lint.pydocstyle]
convention = "numpy"